#!/usr/bin/env python3
"""标签去噪 - 清理frontmatter中的tags，过滤无意义标签"""
import os
import re
import json
from pathlib import Path
from collections import Counter

# 噪声标签模式 - 需要过滤的
NOISE_PATTERNS = [
    # 过短的标签
    r'^C$',
    r'^CA$',
    r'^CAT$',
    r'^CAA$',
    # 纯数字
    r'^\d+$',
    # 常见无意义单词
    r'^(?:the|a|an|and|or|but|in|on|at|to|for|of|with|by|from|as|is|was|are|were|be|been|being|have|has|had|do|does|did|will|would|could|should|may|might|can|shall|this|that|these|those|it|its|they|them|their|we|us|our|you|your|he|she|his|her|him|i|me|my|mine)$',
    # HTML/CSS类名
    r'^class$',
    r'^style$',
    r'^id$',
    r'^href$',
    r'^src$',
    r'^alt$',
    r'^title$',
    r'^width$',
    r'^height$',
    r'^align$',
    r'^valign$',
    r'^colspan$',
    r'^rowspan$',
    r'^border$',
    r'^cellpadding$',
    r'^cellspacing$',
    r'^bgcolor$',
    r'^color$',
    r'^font$',
    r'^size$',
    r'^face$',
    r'^table$',
    r'^tr$',
    r'^td$',
    r'^th$',
    r'^div$',
    r'^span$',
    r'^p$',
    r'^br$',
    r'^hr$',
    r'^ul$',
    r'^ol$',
    r'^li$',
    r'^a$',
    r'^img$',
    r'^pre$',
    r'^code$',
    r'^blockquote$',
    r'^em$',
    r'^strong$',
    r'^b$',
    r'^i$',
    r'^u$',
    r'^s$',
    r'^sub$',
    r'^sup$',
    r'^h1$',
    r'^h2$',
    r'^h3$',
    r'^h4$',
    r'^h5$',
    r'^h6$',
    r'^head$',
    r'^body$',
    r'^html$',
    r'^meta$',
    r'^link$',
    r'^script$',
    r'^noscript$',
    r'^iframe$',
    r'^form$',
    r'^input$',
    r'^button$',
    r'^select$',
    r'^option$',
    r'^textarea$',
    r'^label$',
    r'^fieldset$',
    r'^legend$',
    r'^dl$',
    r'^dt$',
    r'^dd$',
    r'^cite$',
    r'^abbr$',
    r'^acronym$',
    r'^address$',
    r'^dfn$',
    r'^kbd$',
    r'^samp$',
    r'^var$',
    r'^q$',
    r'^ins$',
    r'^del$',
    # 通用编程术语
    r'^NULL$',
    r'^TRUE$',
    r'^FALSE$',
    r'^true$',
    r'^false$',
    r'^int$',
    r'^char$',
    r'^float$',
    r'^double$',
    r'^void$',
    r'^bool$',
    r'^long$',
    r'^short$',
    r'^signed$',
    r'^unsigned$',
    r'^const$',
    r'^static$',
    r'^virtual$',
    r'^inline$',
    r'^extern$',
    r'^public$',
    r'^private$',
    r'^protected$',
    r'^class$',
    r'^struct$',
    r'^enum$',
    r'^union$',
    r'^typedef$',
    r'^template$',
    r'^namespace$',
    r'^using$',
    r'^return$',
    r'^if$',
    r'^else$',
    r'^for$',
    r'^while$',
    r'^do$',
    r'^switch$',
    r'^case$',
    r'^break$',
    r'^continue$',
    r'^goto$',
    r'^try$',
    r'^catch$',
    r'^throw$',
    r'^new$',
    r'^delete$',
    r'^sizeof$',
    r'^typeof$',
    r'^include$',
    r'^define$',
    r'^ifdef$',
    r'^ifndef$',
    r'^endif$',
    r'^pragma$',
    r'^endif$',
    # CAA常见噪声
    r'^HRESULT$',
    r'^S_OK$',
    r'^E_FAIL$',
    r'^E_NOINTERFACE$',
    r'^SUCCEEDED$',
    r'^FAILED$',
    r'^IID_$',
    r'^CLSID_$',
    r'^CATDeclareInterface$',
    r'^CATImplementInterface$',
    r'^CATDeclareClass$',
    r'^CATImplementClass$',
    r'^CATAddRef$',
    r'^CATRelease$',
    r'^CATBaseUnknown$',
    r'^CATCommand$',
    r'^CATDialog$',
    r'^CATNotification$',
    r'^CATCallbackManager$',
    r'^CATStateCommand$',
    r'^CATDlgFrame$',
    r'^CATDlgDialog$',
    r'^IUnknown$',
    r'^IDispatch$',
    r'^REFIID$',
    r'^LPUNKNOWN$',
    r'^LPVOID$',
    r'^DWORD$',
    r'^WORD$',
    r'^BYTE$',
    r'^UINT$',
    r'^ULONG$',
    r'^USHORT$',
    r'^LONG$',
    r'^SHORT$',
    r'^BOOL$',
    r'^LPCTSTR$',
    r'^LPTSTR$',
    r'^LPCSTR$',
    r'^LPSTR$',
    r'^BSTR$',
    r'^VARIANT$',
    r'^SAFEARRAY$',
    r'^CComPtr$',
    r'^CComQIPtr$',
    r'^ATL$',
    r'^MFC$',
    r'^STL$',
    r'^STD$',
    r'^string$',
    r'^vector$',
    r'^map$',
    r'^list$',
    r'^set$',
    r'^queue$',
    r'^stack$',
    r'^deque$',
    r'^array$',
    r'^tuple$',
    r'^pair$',
    r'^iterator$',
    r'^const_iterator$',
    r'^reverse_iterator$',
    r'^size_t$',
    r'^ptrdiff_t$',
    r'^NULL_var$',
    r'^CATSafeRef$',
    r'^CATTry$',
    r'^CATCatch$',
    r'^CATThrow$',
    r'^CATError$',
    r'^CATWarning$',
    r'^CATInformation$',
    r'^CATUnicodeString$',
    r'^CATString$',
    r'^CATPathElement$',
    r'^CATFrmEditor$',
    r'^CATFrmLayout$',
    r'^CATDocument$',
    r'^CATSession$',
    r'^CATContainer$',
    r'^CATElement$',
    r'^CATPart$',
    r'^CATProduct$',
    r'^CATAssembly$',
    r'^CATDrawing$',
    r'^CATSketch$',
    r'^CATBody$',
    r'^CATFace$',
    r'^CATEdge$',
    r'^CATVertex$',
    r'^CATWire$',
    r'^CATLoop$',
    r'^CATLump$',
    r'^CATShell$',
    r'^CATVolume$',
    r'^CATCell$',
    r'^CATDomain$',
    r'^CATBoundary$',
    r'^CATGeometry$',
    r'^CATCurve$',
    r'^CATSurface$',
    r'^CATPoint$',
    r'^CATLine$',
    r'^CATCircle$',
    r'^CATEllipse$',
    r'^CATParabola$',
    r'^CATHyperbola$',
    r'^CATNurbsCurve$',
    r'^CATNurbsSurface$',
    r'^CATPlane$',
    r'^CATCylinder$',
    r'^CATCone$',
    r'^CATSphere$',
    r'^CATTorus$',
    r'^CATRevolutionSurface$',
    r'^CATExtrusionSurface$',
    r'^CATOffsetSurface$',
    r'^CATFilletSurface$',
    r'^CATChamferSurface$',
    r'^CATDraftSurface$',
    r'^CATLaw$',
    r'^CATKnotVector$',
    r'^CATMathPoint$',
    r'^CATMathVector$',
    r'^CATMathDirection$',
    r'^CATMathLine$',
    r'^CATMathPlane$',
    r'^CATMathAxis$',
    r'^CATMathTransformation$',
    r'^CATMathMatrix$',
    r'^CATMathVectorf$',
    r'^CATMathPointf$',
    r'^CATMathDirectionf$',
    r'^CATMathLinef$',
    r'^CATMathPlanef$',
    r'^CATMathAxisf$',
    r'^CATMathTransformationf$',
    r'^CATMathMatrixf$',
    r'^CATMathVector2D$',
    r'^CATMathPoint2D$',
    r'^CATMathDirection2D$',
    r'^CATMathLine2D$',
    r'^CATMathPlane2D$',
    r'^CATMathAxis2D$',
    r'^CATMathTransformation2D$',
    r'^CATMathMatrix2D$',
    r'^CATMathVector2Df$',
    r'^CATMathPoint2Df$',
    r'^CATMathDirection2Df$',
    r'^CATMathLine2Df$',
    r'^CATMathPlane2Df$',
    r'^CATMathAxis2Df$',
    r'^CATMathTransformation2Df$',
    r'^CATMathMatrix2Df$',
    r'^CATMathVector3D$',
    r'^CATMathPoint3D$',
    r'^CATMathDirection3D$',
    r'^CATMathLine3D$',
    r'^CATMathPlane3D$',
    r'^CATMathAxis3D$',
    r'^CATMathTransformation3D$',
    r'^CATMathMatrix3D$',
    r'^CATMathVector3Df$',
    r'^CATMathPoint3Df$',
    r'^CATMathDirection3Df$',
    r'^CATMathLine3Df$',
    r'^CATMathPlane3Df$',
    r'^CATMathAxis3Df$',
    r'^CATMathTransformation3Df$',
    r'^CATMathMatrix3Df$',
    r'^CATMathVector4D$',
    r'^CATMathPoint4D$',
    r'^CATMathDirection4D$',
    r'^CATMathLine4D$',
    r'^CATMathPlane4D$',
    r'^CATMathAxis4D$',
    r'^CATMathTransformation4D$',
    r'^CATMathMatrix4D$',
    r'^CATMathVector4Df$',
    r'^CATMathPoint4Df$',
    r'^CATMathDirection4Df$',
    r'^CATMathLine4Df$',
    r'^CATMathPlane4Df$',
    r'^CATMathAxis4Df$',
    r'^CATMathTransformation4Df$',
    r'^CATMathMatrix4Df$',
    r'^CATMathVector5D$',
    r'^CATMathPoint5D$',
    r'^CATMathDirection5D$',
    r'^CATMathLine5D$',
    r'^CATMathPlane5D$',
    r'^CATMathAxis5D$',
    r'^CATMathTransformation5D$',
    r'^CATMathMatrix5D$',
    r'^CATMathVector5Df$',
    r'^CATMathPoint5Df$',
    r'^CATMathDirection5Df$',
    r'^CATMathLine5Df$',
    r'^CATMathPlane5Df$',
    r'^CATMathAxis5Df$',
    r'^CATMathTransformation5Df$',
    r'^CATMathMatrix5Df$',
    r'^CATMathVector6D$',
    r'^CATMathPoint6D$',
    r'^CATMathDirection6D$',
    r'^CATMathLine6D$',
    r'^CATMathPlane6D$',
    r'^CATMathAxis6D$',
    r'^CATMathTransformation6D$',
    r'^CATMathMatrix6D$',
    r'^CATMathVector6Df$',
    r'^CATMathPoint6Df$',
    r'^CATMathDirection6Df$',
    r'^CATMathLine6Df$',
    r'^CATMathPlane6Df$',
    r'^CATMathAxis6Df$',
    r'^CATMathTransformation6Df$',
    r'^CATMathMatrix6Df$',
    r'^CATMathVector7D$',
    r'^CATMathPoint7D$',
    r'^CATMathDirection7D$',
    r'^CATMathLine7D$',
    r'^CATMathPlane7D$',
    r'^CATMathAxis7D$',
    r'^CATMathTransformation7D$',
    r'^CATMathMatrix7D$',
    r'^CATMathVector7Df$',
    r'^CATMathPoint7Df$',
    r'^CATMathDirection7Df$',
    r'^CATMathLine7Df$',
    r'^CATMathPlane7Df$',
    r'^CATMathAxis7Df$',
    r'^CATMathTransformation7Df$',
    r'^CATMathMatrix7Df$',
    r'^CATMathVector8D$',
    r'^CATMathPoint8D$',
    r'^CATMathDirection8D$',
    r'^CATMathLine8D$',
    r'^CATMathPlane8D$',
    r'^CATMathAxis8D$',
    r'^CATMathTransformation8D$',
    r'^CATMathMatrix8D$',
    r'^CATMathVector8Df$',
    r'^CATMathPoint8Df$',
    r'^CATMathDirection8Df$',
    r'^CATMathLine8Df$',
    r'^CATMathPlane8Df$',
    r'^CATMathAxis8Df$',
    r'^CATMathTransformation8Df$',
    r'^CATMathMatrix8Df$',
    r'^CATMathVector9D$',
    r'^CATMathPoint9D$',
    r'^CATMathDirection9D$',
    r'^CATMathLine9D$',
    r'^CATMathPlane9D$',
    r'^CATMathAxis9D$',
    r'^CATMathTransformation9D$',
    r'^CATMathMatrix9D$',
    r'^CATMathVector9Df$',
    r'^CATMathPoint9Df$',
    r'^CATMathDirection9Df$',
    r'^CATMathLine9Df$',
    r'^CATMathPlane9Df$',
    r'^CATMathAxis9Df$',
    r'^CATMathTransformation9Df$',
    r'^CATMathMatrix9Df$',
    r'^CATMathVector10D$',
    r'^CATMathPoint10D$',
    r'^CATMathDirection10D$',
    r'^CATMathLine10D$',
    r'^CATMathPlane10D$',
    r'^CATMathAxis10D$',
    r'^CATMathTransformation10D$',
    r'^CATMathMatrix10D$',
    r'^CATMathVector10Df$',
    r'^CATMathPoint10Df$',
    r'^CATMathDirection10Df$',
    r'^CATMathLine10Df$',
    r'^CATMathPlane10Df$',
    r'^CATMathAxis10Df$',
    r'^CATMathTransformation10Df$',
    r'^CATMathMatrix10Df$',
    r'^CATMathVector11D$',
    r'^CATMathPoint11D$',
    r'^CATMathDirection11D$',
    r'^CATMathLine11D$',
    r'^CATMathPlane11D$',
    r'^CATMathAxis11D$',
    r'^CATMathTransformation11D$',
    r'^CATMathMatrix11D$',
    r'^CATMathVector11Df$',
    r'^CATMathPoint11Df$',
    r'^CATMathDirection11Df$',
    r'^CATMathLine11Df$',
    r'^CATMathPlane11Df$',
    r'^CATMathAxis11Df$',
    r'^CATMathTransformation11Df$',
    r'^CATMathMatrix11Df$',
    r'^CATMathVector12D$',
    r'^CATMathPoint12D$',
    r'^CATMathDirection12D$',
    r'^CATMathLine12D$',
    r'^CATMathPlane12D$',
    r'^CATMathAxis12D$',
    r'^CATMathTransformation12D$',
    r'^CATMathMatrix12D$',
    r'^CATMathVector12Df$',
    r'^CATMathPoint12Df$',
    r'^CATMathDirection12Df$',
    r'^CATMathLine12Df$',
    r'^CATMathPlane12Df$',
    r'^CATMathAxis12Df$',
    r'^CATMathTransformation12Df$',
    r'^CATMathMatrix12Df$',
    r'^CATMathVector13D$',
    r'^CATMathPoint13D$',
    r'^CATMathDirection13D$',
    r'^CATMathLine13D$',
    r'^CATMathPlane13D$',
    r'^CATMathAxis13D$',
    r'^CATMathTransformation13D$',
    r'^CATMathMatrix13D$',
    r'^CATMathVector13Df$',
    r'^CATMathPoint13Df$',
    r'^CATMathDirection13Df$',
    r'^CATMathLine13Df$',
    r'^CATMathPlane13Df$',
    r'^CATMathAxis13Df$',
    r'^CATMathTransformation13Df$',
    r'^CATMathMatrix13Df$',
    r'^CATMathVector14D$',
    r'^CATMathPoint14D$',
    r'^CATMathDirection14D$',
    r'^CATMathLine14D$',
    r'^CATMathPlane14D$',
    r'^CATMathAxis14D$',
    r'^CATMathTransformation14D$',
    r'^CATMathMatrix14D$',
    r'^CATMathVector14Df$',
    r'^CATMathPoint14Df$',
    r'^CATMathDirection14Df$',
    r'^CATMathLine14Df$',
    r'^CATMathPlane14Df$',
    r'^CATMathAxis14Df$',
    r'^CATMathTransformation14Df$',
    r'^CATMathMatrix14Df$',
    r'^CATMathVector15D$',
    r'^CATMathPoint15D$',
    r'^CATMathDirection15D$',
    r'^CATMathLine15D$',
    r'^CATMathPlane15D$',
    r'^CATMathAxis15D$',
    r'^CATMathTransformation15D$',
    r'^CATMathMatrix15D$',
    r'^CATMathVector15Df$',
    r'^CATMathPoint15Df$',
    r'^CATMathDirection15Df$',
    r'^CATMathLine15Df$',
    r'^CATMathPlane15Df$',
    r'^CATMathAxis15Df$',
    r'^CATMathTransformation15Df$',
    r'^CATMathMatrix15Df$',
    r'^CATMathVector16D$',
    r'^CATMathPoint16D$',
    r'^CATMathDirection16D$',
    r'^CATMathLine16D$',
    r'^CATMathPlane16D$',
    r'^CATMathAxis16D$',
    r'^CATMathTransformation16D$',
    r'^CATMathMatrix16D$',
    r'^CATMathVector16Df$',
    r'^CATMathPoint16Df$',
    r'^CATMathDirection16Df$',
    r'^CATMathLine16Df$',
    r'^CATMathPlane16Df$',
    r'^CATMathAxis16Df$',
    r'^CATMathTransformation16Df$',
    r'^CATMathMatrix16Df$',
    r'^CATMathVector17D$',
    r'^CATMathPoint17D$',
    r'^CATMathDirection17D$',
    r'^CATMathLine17D$',
    r'^CATMathPlane17D$',
    r'^CATMathAxis17D$',
    r'^CATMathTransformation17D$',
    r'^CATMathMatrix17D$',
    r'^CATMathVector17Df$',
    r'^CATMathPoint17Df$',
    r'^CATMathDirection17Df$',
    r'^CATMathLine17Df$',
    r'^CATMathPlane17Df$',
    r'^CATMathAxis17Df$',
    r'^CATMathTransformation17Df$',
    r'^CATMathMatrix17Df$',
    r'^CATMathVector18D$',
    r'^CATMathPoint18D$',
    r'^CATMathDirection18D$',
    r'^CATMathLine18D$',
    r'^CATMathPlane18D$',
    r'^CATMathAxis18D$',
    r'^CATMathTransformation18D$',
    r'^CATMathMatrix18D$',
    r'^CATMathVector18Df$',
    r'^CATMathPoint18Df$',
    r'^CATMathDirection18Df$',
    r'^CATMathLine18Df$',
    r'^CATMathPlane18Df$',
    r'^CATMathAxis18Df$',
    r'^CATMathTransformation18Df$',
    r'^CATMathMatrix18Df$',
    r'^CATMathVector19D$',
    r'^CATMathPoint19D$',
    r'^CATMathDirection19D$',
    r'^CATMathLine19D$',
    r'^CATMathPlane19D$',
    r'^CATMathAxis19D$',
    r'^CATMathTransformation19D$',
    r'^CATMathMatrix19D$',
    r'^CATMathVector19Df$',
    r'^CATMathPoint19Df$',
    r'^CATMathDirection19Df$',
    r'^CATMathLine19Df$',
    r'^CATMathPlane19Df$',
    r'^CATMathAxis19Df$',
    r'^CATMathTransformation19Df$',
    r'^CATMathMatrix19Df$',
    r'^CATMathVector20D$',
    r'^CATMathPoint20D$',
    r'^CATMathDirection20D$',
    r'^CATMathLine20D$',
    r'^CATMathPlane20D$',
    r'^CATMathAxis20D$',
    r'^CATMathTransformation20D$',
    r'^CATMathMatrix20D$',
    r'^CATMathVector20Df$',
    r'^CATMathPoint20Df$',
    r'^CATMathDirection20Df$',
    r'^CATMathLine20Df$',
    r'^CATMathPlane20Df$',
    r'^CATMathAxis20Df$',
    r'^CATMathTransformation20Df$',
    r'^CATMathMatrix20Df$',
    r'^CATMathVector21D$',
    r'^CATMathPoint21D$',
    r'^CATMathDirection21D$',
    r'^CATMathLine21D$',
    r'^CATMathPlane21D$',
    r'^CATMathAxis21D$',
    r'^CATMathTransformation21D$',
    r'^CATMathMatrix21D$',
    r'^CATMathVector21Df$',
    r'^CATMathPoint21Df$',
    r'^CATMathDirection21Df$',
    r'^CATMathLine21Df$',
    r'^CATMathPlane21Df$',
    r'^CATMathAxis21Df$',
    r'^CATMathTransformation21Df$',
    r'^CATMathMatrix21Df$',
    r'^CATMathVector22D$',
    r'^CATMathPoint22D$',
    r'^CATMathDirection22D$',
    r'^CATMathLine22D$',
    r'^CATMathPlane22D$',
    r'^CATMathAxis22D$',
    r'^CATMathTransformation22D$',
    r'^CATMathMatrix22D$',
    r'^CATMathVector22Df$',
    r'^CATMathPoint22Df$',
    r'^CATMathDirection22Df$',
    r'^CATMathLine22Df$',
    r'^CATMathPlane22Df$',
    r'^CATMathAxis22Df$',
    r'^CATMathTransformation22Df$',
    r'^CATMathMatrix22Df$',
    r'^CATMathVector23D$',
    r'^CATMathPoint23D$',
    r'^CATMathDirection23D$',
    r'^CATMathLine23D$',
    r'^CATMathPlane23D$',
    r'^CATMathAxis23D$',
    r'^CATMathTransformation23D$',
    r'^CATMathMatrix23D$',
    r'^CATMathVector23Df$',
    r'^CATMathPoint23Df$',
    r'^CATMathDirection23Df$',
    r'^CATMathLine23Df$',
    r'^CATMathPlane23Df$',
    r'^CATMathAxis23Df$',
    r'^CATMathTransformation23Df$',
    r'^CATMathMatrix23Df$',
    r'^CATMathVector24D$',
    r'^CATMathPoint24D$',
    r'^CATMathDirection24D$',
    r'^CATMathLine24D$',
    r'^CATMathPlane24D$',
    r'^CATMathAxis24D$',
    r'^CATMathTransformation24D$',
    r'^CATMathMatrix24D$',
    r'^CATMathVector24Df$',
    r'^CATMathPoint24Df$',
    r'^CATMathDirection24Df$',
    r'^CATMathLine24Df$',
    r'^CATMathPlane24Df$',
    r'^CATMathAxis24Df$',
    r'^CATMathTransformation24Df$',
    r'^CATMathMatrix24Df$',
    r'^CATMathVector25D$',
    r'^CATMathPoint25D$',
    r'^CATMathDirection25D$',
    r'^CATMathLine25D$',
    r'^CATMathPlane25D$',
    r'^CATMathAxis25D$',
    r'^CATMathTransformation25D$',
    r'^CATMathMatrix25D$',
    r'^CATMathVector25Df$',
    r'^CATMathPoint25Df$',
    r'^CATMathDirection25Df$',
    r'^CATMathLine25Df$',
    r'^CATMathPlane25Df$',
    r'^CATMathAxis25Df$',
    r'^CATMathTransformation25Df$',
    r'^CATMathMatrix25Df$',
    r'^CATMathVector26D$',
    r'^CATMathPoint26D$',
    r'^CATMathDirection26D$',
    r'^CATMathLine26D$',
    r'^CATMathPlane26D$',
    r'^CATMathAxis26D$',
    r'^CATMathTransformation26D$',
    r'^CATMathMatrix26D$',
    r'^CATMathVector26Df$',
    r'^CATMathPoint26Df$',
    r'^CATMathDirection26Df$',
    r'^CATMathLine26Df$',
    r'^CATMathPlane26Df$',
    r'^CATMathAxis26Df$',
    r'^CATMathTransformation26Df$',
    r'^CATMathMatrix26Df$',
    r'^CATMathVector27D$',
    r'^CATMathPoint27D$',
    r'^CATMathDirection27D$',
    r'^CATMathLine27D$',
    r'^CATMathPlane27D$',
    r'^CATMathAxis27D$',
    r'^CATMathTransformation27D$',
    r'^CATMathMatrix27D$',
    r'^CATMathVector27Df$',
    r'^CATMathPoint27Df$',
    r'^CATMathDirection27Df$',
    r'^CATMathLine27Df$',
    r'^CATMathPlane27Df$',
    r'^CATMathAxis27Df$',
    r'^CATMathTransformation27Df$',
    r'^CATMathMatrix27Df$',
    r'^CATMathVector28D$',
    r'^CATMathPoint28D$',
    r'^CATMathDirection28D$',
    r'^CATMathLine28D$',
    r'^CATMathPlane28D$',
    r'^CATMathAxis28D$',
    r'^CATMathTransformation28D$',
    r'^CATMathMatrix28D$',
    r'^CATMathVector28Df$',
    r'^CATMathPoint28Df$',
    r'^CATMathDirection28Df$',
    r'^CATMathLine28Df$',
    r'^CATMathPlane28Df$',
    r'^CATMathAxis28Df$',
    r'^CATMathTransformation28Df$',
    r'^CATMathMatrix28Df$',
    r'^CATMathVector29D$',
    r'^CATMathPoint29D$',
    r'^CATMathDirection29D$',
    r'^CATMathLine29D$',
    r'^CATMathPlane29D$',
    r'^CATMathAxis29D$',
    r'^CATMathTransformation29D$',
    r'^CATMathMatrix29D$',
    r'^CATMathVector29Df$',
    r'^CATMathPoint29Df$',
    r'^CATMathDirection29Df$',
    r'^CATMathLine29Df$',
    r'^CATMathPlane29Df$',
    r'^CATMathAxis29Df$',
    r'^CATMathTransformation29Df$',
    r'^CATMathMatrix29Df$',
    r'^CATMathVector30D$',
    r'^CATMathPoint30D$',
    r'^CATMathDirection30D$',
    r'^CATMathLine30D$',
    r'^CATMathPlane30D$',
    r'^CATMathAxis30D$',
    r'^CATMathTransformation30D$',
    r'^CATMathMatrix30D$',
    r'^CATMathVector30Df$',
    r'^CATMathPoint30Df$',
    r'^CATMathDirection30Df$',
    r'^CATMathLine30Df$',
    r'^CATMathPlane30Df$',
    r'^CATMathAxis30Df$',
    r'^CATMathTransformation30Df$',
    r'^CATMathMatrix30Df$',
]

# 编译正则
NOISE_REGEX = [re.compile(p, re.IGNORECASE) for p in NOISE_PATTERNS]


def is_noise(tag):
    """判断标签是否为噪声"""
    for pattern in NOISE_REGEX:
        if pattern.match(tag):
            return True
    return False


def denoise_tags(tags):
    """去噪标签列表"""
    cleaned = []
    for tag in tags:
        tag = tag.strip()
        if not tag:
            continue
        if len(tag) < 3:
            continue
        if is_noise(tag):
            continue
        cleaned.append(tag)
    return cleaned


def process_file(filepath):
    """处理单个markdown文件"""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return False

    # 查找frontmatter中的tags
    match = re.search(r'^tags:\s*(\[.*?\])', content, re.MULTILINE | re.DOTALL)
    if not match:
        return False

    try:
        old_tags = json.loads(match.group(1))
    except json.JSONDecodeError:
        return False

    new_tags = denoise_tags(old_tags)

    if len(new_tags) == len(old_tags):
        return False  # 没有变化

    # 替换tags行
    new_tags_str = json.dumps(new_tags, ensure_ascii=False)
    new_content = re.sub(
        r'^(tags:\s*)\[.*?\]',
        f'tags: {new_tags_str}',
        content,
        flags=re.MULTILINE | re.DOTALL,
        count=1
    )

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)

    return True


def main():
    base_dir = Path('CAAKnowledge/use-cases')
    if not base_dir.exists():
        print(f"Directory not found: {base_dir}")
        return

    changed = 0
    total = 0
    all_tags = Counter()

    for md_file in base_dir.rglob('*.md'):
        total += 1
        if process_file(md_file):
            changed += 1

        # 统计去噪后的标签
        try:
            with open(md_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            match = re.search(r'^tags:\s*(\[.*?\])', content, re.MULTILINE | re.DOTALL)
            if match:
                try:
                    tags = json.loads(match.group(1))
                    for t in tags:
                        all_tags[t] += 1
                except:
                    pass
        except:
            pass

    print(f"Processed {total} files, changed {changed} files")
    print(f"\nTop 30 tags after denoising:")
    for tag, count in all_tags.most_common(30):
        print(f"  {tag}: {count}")


if __name__ == '__main__':
    main()
